# Form implementation generated from reading ui file 'AddViolationForm.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import bd_main
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_AddViolationForm(object):
    def setupUi(self, AddViolationForm):
        self.con = bd_main.connect()
        self.mycursor = self.con.cursor()
        AddViolationForm.setObjectName("AddViolationForm")
        AddViolationForm.resize(500, 200)
        self.AddViolationLabel = QtWidgets.QLabel(AddViolationForm)
        self.AddViolationLabel.setGeometry(QtCore.QRect(0, 30, 500, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AddViolationLabel.setFont(font)
        self.AddViolationLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.AddViolationLabel.setObjectName("AddViolationLabel")
        self.ViolationLabel = QtWidgets.QLabel(AddViolationForm)
        self.ViolationLabel.setGeometry(QtCore.QRect(35, 70, 72, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ViolationLabel.setFont(font)
        self.ViolationLabel.setObjectName("ViolationLabel")
        self.ViolationPlainText = QtWidgets.QPlainTextEdit(AddViolationForm)
        self.ViolationPlainText.setGeometry(QtCore.QRect(115, 67, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ViolationPlainText.setFont(font)
        self.ViolationPlainText.setObjectName("ViolationPlainText")
        self.SumLabel = QtWidgets.QLabel(AddViolationForm)
        self.SumLabel.setGeometry(QtCore.QRect(35, 110, 42, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SumLabel.setFont(font)
        self.SumLabel.setObjectName("SumLabel")
        self.SumPlainText = QtWidgets.QPlainTextEdit(AddViolationForm)
        self.SumPlainText.setGeometry(QtCore.QRect(115, 107, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SumPlainText.setFont(font)
        self.SumPlainText.setObjectName("SumPlainText")
        self.ApplyBtn = QtWidgets.QPushButton(AddViolationForm)
        self.ApplyBtn.setGeometry(QtCore.QRect(405, 150, 75, 23))
        self.ApplyBtn.setEnabled(False)
        self.ApplyBtn.setObjectName("ApplyBtn")

        self.retranslateUi(AddViolationForm)
        QtCore.QMetaObject.connectSlotsByName(AddViolationForm)

        self.ViolationPlainText.textChanged.connect(lambda: self.ViolationText_slot())
        self.SumPlainText.textChanged.connect(lambda: self.SumText_slot())
        self.ApplyBtn.clicked.connect(lambda: self.AddViolation())

    def retranslateUi(self, AddViolationForm):
        _translate = QtCore.QCoreApplication.translate
        AddViolationForm.setWindowTitle(_translate("AddViolationForm", "Добавления нарушения"))
        self.AddViolationLabel.setText(_translate("AddViolationForm", "Добавление нарушения"))
        self.ViolationLabel.setText(_translate("AddViolationForm", "Нарушение:"))
        self.SumLabel.setText(_translate("AddViolationForm", "Сумма:"))
        self.ApplyBtn.setText(_translate("AddViolationForm", "Принять"))

    def ViolationText_slot(self):
        self.violation = self.ViolationPlainText.toPlainText()
        if (len(self.violation) > 0):
            self.ApplyBtn.setEnabled(True)
        else:
            self.ApplyBtn.setEnabled(False)

    def SumText_slot(self):
        self.sum = self.SumPlainText.toPlainText()
        if (len(self.sum) > 0):
            self.ApplyBtn.setEnabled(True)
        else:
            self.ApplyBtn.setEnabled(False)

    def AddViolation(self):
        query = f"SELECT violation_ID FROM violation_list WHERE violation = '{self.violation}';"
        self.mycursor.execute(query)
        self.con.commit()
        violations = self.mycursor.fetchall()

        if (len(violations) > 0):
            Error = QMessageBox()
            Error.setWindowTitle("Ошибка")
            Error.setText("Данный штраф уже внесен в список")
            Error.setIcon(QMessageBox.Icon.Warning)
            Error.exec()
        else:
            query = f"INSERT INTO violation_list (violation, sum) VALUES ('{self.violation}', {int(self.sum)});"
            self.mycursor.execute(query)
            self.con.commit()
            Success = QMessageBox()
            Success.setWindowTitle("Выполнено")
            Success.setText("Нарушение добавлено в список")
            Success.setIcon(QMessageBox.Icon.Information)
            Success.exec()