# Form implementation generated from reading ui file 'ChangeFineSum.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import bd_main


class Ui_ChangeFineSum(object):
    def setupUi(self, ChangeFineSum):
        self.con = bd_main.connect()
        self.mycursor = self.con.cursor()
        ChangeFineSum.setObjectName("ChangeFineSum")
        ChangeFineSum.resize(400, 230)
        self.ChangeFineSumLabel = QtWidgets.QLabel(ChangeFineSum)
        self.ChangeFineSumLabel.setGeometry(QtCore.QRect(0, 30, 400, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ChangeFineSumLabel.setFont(font)
        self.ChangeFineSumLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ChangeFineSumLabel.setObjectName("ChangeFineSumLabel")
        self.FineLabel = QtWidgets.QLabel(ChangeFineSum)
        self.FineLabel.setGeometry(QtCore.QRect(30, 70, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FineLabel.setFont(font)
        self.FineLabel.setObjectName("FineLabel")
        self.ViolationPlainText = QtWidgets.QPlainTextEdit(ChangeFineSum)
        self.ViolationPlainText.setGeometry(QtCore.QRect(90, 68, 250, 25))
        self.ViolationPlainText.setObjectName("ViolationPlainText")
        self.ClearViolationBtn = QtWidgets.QPushButton(ChangeFineSum)
        self.ClearViolationBtn.setGeometry(QtCore.QRect(314, 67, 27, 27))
        self.ClearViolationBtn.setObjectName("ClearViolationBtn")
        self.CurrentSum = QtWidgets.QLabel(ChangeFineSum)
        self.CurrentSum.setGeometry(QtCore.QRect(30, 110, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CurrentSum.setFont(font)
        self.CurrentSum.setObjectName("CurrentSum")
        self.NewSum = QtWidgets.QLabel(ChangeFineSum)
        self.NewSum.setGeometry(QtCore.QRect(30, 145, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NewSum.setFont(font)
        self.NewSum.setObjectName("NewSum")
        self.textBrowser = QtWidgets.QTextBrowser(ChangeFineSum)
        self.textBrowser.setGeometry(QtCore.QRect(150, 106, 100, 30))
        self.textBrowser.setObjectName("textBrowser")
        self.NewSumPlainText = QtWidgets.QPlainTextEdit(ChangeFineSum)
        self.NewSumPlainText.setGeometry(QtCore.QRect(150, 141, 100, 30))
        self.NewSumPlainText.setObjectName("plainTextEdit")
        self.ApplyBtn = QtWidgets.QPushButton(ChangeFineSum)
        self.ApplyBtn.setGeometry(QtCore.QRect(305, 185, 75, 23))
        self.ApplyBtn.setEnabled(False)
        self.ApplyBtn.setObjectName("ApplyBtn")
        self.ViolationList = QtWidgets.QListWidget(ChangeFineSum)
        self.ViolationList.setGeometry(QtCore.QRect(90, 92, 250, 130))
        self.ViolationList.setSelectionRectVisible(False)
        self.ViolationList.setVisible(False)
        self.ViolationList.setObjectName("ViolationList")

        self.retranslateUi(ChangeFineSum)
        QtCore.QMetaObject.connectSlotsByName(ChangeFineSum)

        self.ViolationPlainText.textChanged.connect(lambda: self.FillViolationList())
        self.ClearViolationBtn.clicked.connect(lambda: self.ClearViolation())
        self.ViolationList.itemActivated.connect(lambda: self.SetFine(self.ViolationList.currentItem()))
        self.NewSumPlainText.textChanged.connect(lambda: self.Sum_slot())

    def retranslateUi(self, ChangeFineSum):
        _translate = QtCore.QCoreApplication.translate
        ChangeFineSum.setWindowTitle(_translate("ChangeFineSum", "Изменение размера штрафа"))
        self.ChangeFineSumLabel.setText(_translate("ChangeFineSum", "Изменение размера штрафа"))
        self.FineLabel.setText(_translate("ChangeFineSum", "Штраф:"))
        self.ClearViolationBtn.setText(_translate("ChangeFineSum", "✕"))
        self.CurrentSum.setText(_translate("ChangeFineSum", "Нынешняя сумма:"))
        self.NewSum.setText(_translate("ChangeFineSum", "Новая сумма:"))
        self.ApplyBtn.setText(_translate("ChangeFineSum", "Принять"))

    def ClearViolation(self):
        self.ViolationPlainText.clear()
        self.textBrowser.clear()

    def AddItemToList(self, violation):
        self.ViolationList.addItem(violation)

    def Sum_slot(self):
        self.sum = self.NewSumPlainText.toPlainText()
        if (len(self.sum) > 0):
            self.ApplyBtn.setEnabled(True)
        else:
            self.ApplyBtn.setEnabled(False)

    def FillViolationList(self):
        self.violation = self.ViolationPlainText.toPlainText()
        self.ViolationList.clear()
        #self.ViolationList.setVisible(False)
        if (len(self.violation) == 0):
            self.ViolationList.clear()
            self.NewSumPlainText.clear()
            self.ViolationList.setVisible(False)
            self.ApplyBtn.setEnabled(False)
        else:
            #self.ApplyBtn.setEnabled(True)
            self.ViolationList.setVisible(True)
            query = f"SELECT violation FROM violation_list WHERE violation LIKE '%{self.violation}%'"
            self.mycursor.execute(query)
            self.con.commit()
            allViolations = self.mycursor.fetchall()
            for i in range(0, len(allViolations)):
                self.AddItemToList(allViolations[i][0])

    def SetFine(self, item):
        print("=", str(item.text()), "=")
        self.ViolationPlainText.setPlainText(str(item.text()))
        print("fff")
        #print("=", str(item.text()), "=")
        self.ViolationList.setVisible(False)
        query = f"SELECT sum FROM violation_list WHERE violation = '{self.violation}'"
        print(query)
        self.mycursor.execute(query)
        self.con.commit()
        (sum,) = self.mycursor.fetchone()
        self.textBrowser.setText(str(sum))