# Form implementation generated from reading ui file 'GoodDriversForm.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QHeaderView
import bd_main


class Ui_GoodDriversForm(object):
    def setupUi(self, GoodDriversForm):
        self.con = bd_main.connect()
        self.mycursor = self.con.cursor()
        GoodDriversForm.setObjectName("GoodDriversForm")
        GoodDriversForm.resize(500, 400)
        self.ListLabel = QtWidgets.QLabel(GoodDriversForm)
        self.ListLabel.setGeometry(QtCore.QRect(0, 30, 500, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ListLabel.setFont(font)
        self.ListLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ListLabel.setWordWrap(True)
        self.ListLabel.setObjectName("ListLabel")
        self.tableWidget = QtWidgets.QTableWidget(GoodDriversForm)
        self.tableWidget.setGeometry(QtCore.QRect(30, 70, 440, 300))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger(False))


        self.retranslateUi(GoodDriversForm)
        QtCore.QMetaObject.connectSlotsByName(GoodDriversForm)

        self.FillTable()

    def retranslateUi(self, GoodDriversForm):
        _translate = QtCore.QCoreApplication.translate
        GoodDriversForm.setWindowTitle(_translate("GoodDriversForm", "Список хороших водителей"))
        self.ListLabel.setText(_translate("GoodDriversForm", "Список водитилей, не имеющих нарушений"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("GoodDriversForm", "ID водителя"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("GoodDriversForm", "ФИО"))

    def AddRow(self, driver_ID, FCS):
        rowPosition = self.tableWidget.rowCount()
        self.tableWidget.insertRow(rowPosition)

        self.tableWidget.setItem(rowPosition, 0, QtWidgets.QTableWidgetItem(str(driver_ID)))
        self.tableWidget.setItem(rowPosition, 1, QtWidgets.QTableWidgetItem(FCS))

    def FillTable(self):
        query = f"SELECT driver_ID, FCS FROM driver_list WHERE fine_count = 0;"
        self.mycursor.execute(query)
        self.con.commit()
        allDrivers = self.mycursor.fetchall()
        for i in range(0, len(allDrivers)):
            query = f"SELECT status FROM car WHERE driver_id = {allDrivers[i][0]} and status = 'Стоит на учете';"
            self.mycursor.execute(query)
            self.con.commit()
            cars = self.mycursor.fetchall()
            if (len(cars) != 0):
                self.AddRow(allDrivers[i][0], allDrivers[i][1])