# Form implementation generated from reading ui file 'MainMenu.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt6 import QtCore, QtGui, QtWidgets
import AddDriverWidget
import bd_main
import TableOfDrivers
import FineRegisterForm
import CarRegisterForm
import LogTable
import FinePaymentReg
import BankStatement
import ProfitForm
import GoodDriversForm
import BadDriversForm
import ChangeFineSum
import ViolationStatisticks
import LetterToGoodBoy
import LetterToBadBoy
import AddViolationForm
#from PyQt6.QtWidgets import QApplication, QDialog, QMainWindow
#from AddDriverDialog import Ui_Dialog



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.con = bd_main.connect()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 430)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AddDriverBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AddDriverBtn.setGeometry(QtCore.QRect(30, 70, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AddDriverBtn.setFont(font)
        self.AddDriverBtn.setObjectName("AddDriverBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 30, 230, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.ShowDriversBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ShowDriversBtn.setGeometry(QtCore.QRect(30, 170, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ShowDriversBtn.setFont(font)
        self.ShowDriversBtn.setObjectName("ShowDriversBtn")

        self.FineRegisterBtn = QtWidgets.QPushButton(self.centralwidget)
        self.FineRegisterBtn.setGeometry(QtCore.QRect(30, 120, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FineRegisterBtn.setFont(font)
        self.FineRegisterBtn.setObjectName("FineRegisterBtn")

        self.CarRegisterBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CarRegisterBtn.setGeometry(QtCore.QRect(260, 120, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CarRegisterBtn.setFont(font)
        self.CarRegisterBtn.setObjectName("CarRegisterBtn")

        self.DriverLogBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DriverLogBtn.setGeometry(QtCore.QRect(145, 370, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DriverLogBtn.setFont(font)
        self.DriverLogBtn.setObjectName("DriverLogBtn")

        self.FinePaymentBtn = QtWidgets.QPushButton(self.centralwidget)
        self.FinePaymentBtn.setGeometry(QtCore.QRect(260, 170, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FinePaymentBtn.setFont(font)
        self.FinePaymentBtn.setObjectName("FinePaymentBtn")

        self.BankStatementBtn = QtWidgets.QPushButton(self.centralwidget)
        self.BankStatementBtn.setGeometry(QtCore.QRect(30, 220, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BankStatementBtn.setFont(font)
        self.BankStatementBtn.setObjectName("BankStatementBtn")

        self.ProfitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ProfitBtn.setGeometry(QtCore.QRect(260, 220, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ProfitBtn.setFont(font)
        self.ProfitBtn.setObjectName("ProfitBtn")

        self.GoodDriversBtn = QtWidgets.QPushButton(self.centralwidget)
        self.GoodDriversBtn.setGeometry(QtCore.QRect(30, 270, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GoodDriversBtn.setFont(font)
        self.GoodDriversBtn.setObjectName("GoodDriversBtn")

        self.BadDriversBtn = QtWidgets.QPushButton(self.centralwidget)
        self.BadDriversBtn.setGeometry(QtCore.QRect(260, 270, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BadDriversBtn.setFont(font)
        self.BadDriversBtn.setObjectName("BadDriversBtn")

        self.ChangeFineSumBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ChangeFineSumBtn.setGeometry(QtCore.QRect(30, 320, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ChangeFineSumBtn.setFont(font)
        self.ChangeFineSumBtn.setObjectName("ChangeFineSumBtn")

        self.ViolationStatisticksBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ViolationStatisticksBtn.setGeometry(QtCore.QRect(260, 320, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ViolationStatisticksBtn.setFont(font)
        self.ViolationStatisticksBtn.setObjectName("ViolationStatisticksBtn")

        self.AddViolationBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AddViolationBtn.setGeometry(QtCore.QRect(260, 70, 210, 40)) #145, 370
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AddViolationBtn.setFont(font)
        self.AddViolationBtn.setObjectName("AddViolationBtn")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.AddDriverBtn.clicked.connect(lambda: self.OpenAddDriverWin())
        self.ShowDriversBtn.clicked.connect(lambda: self.OpenTableOfDriversWin())
        self.FineRegisterBtn.clicked.connect(lambda: self.OpenFineRegisterForm())
        self.CarRegisterBtn.clicked.connect(lambda: self.OpenCarRegisterForm())
        self.DriverLogBtn.clicked.connect(lambda: self.OpenDriverLogTableForm())
        self.FinePaymentBtn.clicked.connect(lambda: self.OpenFinePaymentRegForm())
        self.BankStatementBtn.clicked.connect(lambda: self.OpenBankStatementTable())
        self.ProfitBtn.clicked.connect(lambda: self.OpenProfitForm())
        self.GoodDriversBtn.clicked.connect(lambda: self.OpenGoodDriversForm())
        self.BadDriversBtn.clicked.connect(lambda: self.OpenBadDriversForm())
        self.ChangeFineSumBtn.clicked.connect(lambda: self.OpenChangeFineSumForm())
        self.ViolationStatisticksBtn.clicked.connect(lambda: self.OpenViolationStatisticksForm())
        self.AddViolationBtn.clicked.connect(lambda: self.OpenAddViolationForm())

        #self.AddDriver()
        #self.OpenAddDriverWin()

        self.OpenGoodBoy()
        self.OpenBadBoy()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "База данных ГИБДД"))
        self.AddDriverBtn.setText(_translate("MainWindow", "Добавить водителя"))
        self.label.setText(_translate("MainWindow", "Меню базы данных ГИБДД"))
        self.ShowDriversBtn.setText(_translate("MainWindow", "Показать список водителей"))
        self.FineRegisterBtn.setText(_translate("MainWindow", "Выписать штраф"))
        self.CarRegisterBtn.setText(_translate("MainWindow", "Управление учетом автомобилей"))
        self.DriverLogBtn.setText(_translate("MainWindow", "Заказать историю водителя"))
        self.FinePaymentBtn.setText(_translate("MainWindow", "Оплата штрафа"))
        self.BankStatementBtn.setText(_translate("MainWindow", "Банковская выписка"))
        self.ProfitBtn.setText(_translate("MainWindow", "Посмотреть прибыль"))
        self.GoodDriversBtn.setText(_translate("MainWindow", "Список хороших водителей"))
        self.BadDriversBtn.setText(_translate("MainWindow", "Список злостных водителей"))
        self.ChangeFineSumBtn.setText(_translate("MainWindow", "Изменить размер штрафа"))
        self.ViolationStatisticksBtn.setText(_translate("MainWindow", "Статистика по нарушениям"))
        self.AddViolationBtn.setText(_translate("MainWindow", "Добавить нарушение"))

    def OpenAddDriverWin(self):
        Dialog = QtWidgets.QDialog()
        ui = AddDriverWidget.Ui_Form()
        ui.setupUi(Dialog)
        Dialog.exec()

    def OpenTableOfDriversWin(self):
        Table = QtWidgets.QDialog()
        ui = TableOfDrivers.Ui_Form()
        ui.setupUi(Table)
        Table.exec()

    def OpenFineRegisterForm(self):
        FineRegister = QtWidgets.QDialog()
        ui = FineRegisterForm.Ui_FineRegisterForm()
        ui.setupUi(FineRegister)
        FineRegister.exec()

    def OpenCarRegisterForm(self):
        CarRegister = QtWidgets.QDialog()
        ui = CarRegisterForm.Ui_CarRegisterForm()
        ui.setupUi(CarRegister)
        CarRegister.exec()

    def OpenDriverLogTableForm(self):
        DriverLog = QtWidgets.QDialog()
        ui = LogTable.Ui_Form()
        ui.setupUi(DriverLog)
        DriverLog.exec()

    def OpenFinePaymentRegForm(self):
        FinePayment = QtWidgets.QDialog()
        ui = FinePaymentReg.Ui_FinePaymentReg()
        ui.setupUi(FinePayment)
        FinePayment.exec()

    def OpenBankStatementTable(self):
        BankStatementWin = QtWidgets.QDialog()
        ui = BankStatement.Ui_BankChecks()
        ui.setupUi(BankStatementWin)
        BankStatementWin.exec()

    def OpenProfitForm(self):
        Profit = QtWidgets.QDialog()
        ui = ProfitForm.Ui_ProfitForm()
        ui.setupUi(Profit)
        Profit.exec()

    def OpenGoodDriversForm(self):
        GoodDrivers = QtWidgets.QDialog()
        ui = GoodDriversForm.Ui_GoodDriversForm()
        ui.setupUi(GoodDrivers)
        GoodDrivers.exec()

    def OpenBadDriversForm(self):
        BadDrivers = QtWidgets.QDialog()
        ui = BadDriversForm.Ui_BadDriversForm()
        ui.setupUi(BadDrivers)
        BadDrivers.exec()

    def OpenChangeFineSumForm(self):
        ChangeFine = QtWidgets.QDialog()
        ui = ChangeFineSum.Ui_ChangeFineSum()
        ui.setupUi(ChangeFine)
        ChangeFine.exec()

    def OpenViolationStatisticksForm(self):
        ViolationStats = QtWidgets.QDialog()
        ui = ViolationStatisticks.Ui_ViolationStatisticks()
        ui.setupUi(ViolationStats)
        ViolationStats.exec()

    def OpenGoodBoy(self):
        LetterToGoodBoy.CheckForGoodBoys()

    def OpenBadBoy(self):
        LetterToBadBoy.CheckForBadBoys()

    def OpenAddViolationForm(self):
        AddViolation = QtWidgets.QDialog()
        ui = AddViolationForm.Ui_AddViolationForm()
        ui.setupUi(AddViolation)
        AddViolation.exec()